### ISSUE TITLE
Issue With Vanity Joins

### ISSUE THREAD

**Issue by xathail** [xzerios/ReferCord#1]
Basically, what the code is meant to do is allow the user to create and be allocated an invite from the bot - so the bot creates the invite (this allows the user to be given one of the bot's invites which means they can have a permanent invite that has unlimited uses)

The bot then tracks the joins and if the invite matches one of the created ones, it'll save the joiners UserID to that invite.

It uses the bot's invites to challenge the current way of invite logging as it is quite inefficient, with most invite trackers failing to store joins from temporary invites (which vanities often make you have to use if you want your own invite)

The issue with vanity joins is that the bot saves the UserIDs of people joining from the vanity as the bot invite with the most recent join.

For example, say I have bot invite x and someone has bot invite y.
Someone joins from invite y and that's fine because it saves the joiner's UserID alongside the y invite.
However, if someone then joins the server with the vanity invite, it'll save the userID to y's invite and make it seem like they joined the server from the bot invite instead.

**Comment by AaravMalani** [comment]
on it hold on
